# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Country.create([{"name"=>"Afghanistan","alpha"=>"AF","code"=>"004"},{"name"=>"Åland Islands","alpha"=>"AX","code"=>"248"},{"name"=>"Albania","alpha"=>"AL","code"=>"008"},{"name"=>"Algeria","alpha"=>"DZ","code"=>"012"},{"name"=>"American Samoa","alpha"=>"AS","code"=>"016"},{"name"=>"Andorra","alpha"=>"AD","code"=>"020"},{"name"=>"Angola","alpha"=>"AO","code"=>"024"},{"name"=>"Anguilla","alpha"=>"AI","code"=>"660"},{"name"=>"Antarctica","alpha"=>"AQ","code"=>"010"},{"name"=>"Antigua and Barbuda","alpha"=>"AG","code"=>"028"},{"name"=>"Argentina","alpha"=>"AR","code"=>"032"},{"name"=>"Armenia","alpha"=>"AM","code"=>"051"},{"name"=>"Aruba","alpha"=>"AW","code"=>"533"},{"name"=>"Australia","alpha"=>"AU","code"=>"036"},{"name"=>"Austria","alpha"=>"AT","code"=>"040"},{"name"=>"Azerbaijan","alpha"=>"AZ","code"=>"031"}])
Country.create([{"name"=>"Bahamas","alpha"=>"BS","code"=>"044"},{"name"=>"Bahrain","alpha"=>"BH","code"=>"048"},{"name"=>"Bangladesh","alpha"=>"BD","code"=>"050"},{"name"=>"Barbados","alpha"=>"BB","code"=>"052"},{"name"=>"Belarus","alpha"=>"BY","code"=>"112"},{"name"=>"Belgium","alpha"=>"BE","code"=>"056"},{"name"=>"Belize","alpha"=>"BZ","code"=>"084"},{"name"=>"Benin","alpha"=>"BJ","code"=>"204"},{"name"=>"Bermuda","alpha"=>"BM","code"=>"060"},{"name"=>"Bhutan","alpha"=>"BT","code"=>"064"},{"name"=>"Bolivia, Plurinational State of","alpha"=>"BO","code"=>"068"},{"name"=>"Bonaire, Sint Eustatius and Saba","alpha"=>"BQ","code"=>"535"},{"name"=>"Bosnia and Herzegovina","alpha"=>"BA","code"=>"070"},{"name"=>"Botswana","alpha"=>"BW","code"=>"072"},{"name"=>"Bouvet Island","alpha"=>"BV","code"=>"074"},{"name"=>"Brazil","alpha"=>"BR","code"=>"076"},{"name"=>"British Indian Ocean Territory","alpha"=>"IO","code"=>"086"},{"name"=>"Brunei Darussalam","alpha"=>"BN","code"=>"096"},{"name"=>"Bulgaria","alpha"=>"BG","code"=>"100"},{"name"=>"Burkina Faso","alpha"=>"BF","code"=>"854"},{"name"=>"Burundi","alpha"=>"BI","code"=>"108"}])
Country.create([{"name"=>"Cambodia","alpha"=>"KH","code"=>"116"},{"name"=>"Cameroon","alpha"=>"CM","code"=>"120"},{"name"=>"Canada","alpha"=>"CA","code"=>"124"},{"name"=>"Cape Verde","alpha"=>"CV","code"=>"132"},{"name"=>"Cayman Islands","alpha"=>"KY","code"=>"136"},{"name"=>"Central African Republic","alpha"=>"CF","code"=>"140"},{"name"=>"Chad","alpha"=>"TD","code"=>"148"},{"name"=>"Chile","alpha"=>"CL","code"=>"152"},{"name"=>"China","alpha"=>"CN","code"=>"156"},{"name"=>"Christmas Island","alpha"=>"CX","code"=>"162"},{"name"=>"Cocos (Keeling) Islands","alpha"=>"CC","code"=>"166"},{"name"=>"Colombia","alpha"=>"CO","code"=>"170"},{"name"=>"Comoros","alpha"=>"KM","code"=>"174"},{"name"=>"Congo","alpha"=>"CG","code"=>"178"},{"name"=>"Congo, the Democratic Republic of the","alpha"=>"CD","code"=>"180"},{"name"=>"Cook Islands","alpha"=>"CK","code"=>"184"},{"name"=>"Costa Rica","alpha"=>"CR","code"=>"188"},{"name"=>"Côte d'Ivoire","alpha"=>"CI","code"=>"384"},{"name"=>"Croatia","alpha"=>"HR","code"=>"191"},{"name"=>"Cuba","alpha"=>"CU","code"=>"192"},{"name"=>"Curaçao","alpha"=>"CW","code"=>"531"},{"name"=>"Cyprus","alpha"=>"CY","code"=>"196"},{"name"=>"Czech Republic","alpha"=>"CZ","code"=>"203"}])
Country.create([{"name"=>"Denmark","alpha"=>"DK","code"=>"208"},{"name"=>"Djibouti","alpha"=>"DJ","code"=>"262"},{"name"=>"Dominica","alpha"=>"DM","code"=>"212"},{"name"=>"Dominican Republic","alpha"=>"DO","code"=>"214"}])
Country.create([{"name"=>"Ecuador","alpha"=>"EC","code"=>"218"},{"name"=>"Egypt","alpha"=>"EG","code"=>"818"},{"name"=>"El Salvador","alpha"=>"SV","code"=>"222"},{"name"=>"Equatorial Guinea","alpha"=>"GQ","code"=>"226"},{"name"=>"Eritrea","alpha"=>"ER","code"=>"232"},{"name"=>"Estonia","alpha"=>"EE","code"=>"233"},{"name"=>"Ethiopia","alpha"=>"ET","code"=>"231"}])
Country.create([{"name"=>"Falkland Islands (Malvinas)","alpha"=>"FK","code"=>"238"},{"name"=>"Faroe Islands","alpha"=>"FO","code"=>"234"},{"name"=>"Fiji","alpha"=>"FJ","code"=>"242"},{"name"=>"Finland","alpha"=>"FI","code"=>"246"},{"name"=>"France","alpha"=>"FR","code"=>"250"},{"name"=>"French Guiana","alpha"=>"GF","code"=>"254"},{"name"=>"French Polynesia","alpha"=>"PF","code"=>"258"},{"name"=>"French Southern Territories","alpha"=>"TF","code"=>"260"}])
Country.create([{"name"=>"Gabon","alpha"=>"GA","code"=>"266"},{"name"=>"Gambia","alpha"=>"GM","code"=>"270"},{"name"=>"Georgia","alpha"=>"GE","code"=>"268"},{"name"=>"Germany","alpha"=>"DE","code"=>"276"},{"name"=>"Ghana","alpha"=>"GH","code"=>"288"},{"name"=>"Gibraltar","alpha"=>"GI","code"=>"292"},{"name"=>"Greece","alpha"=>"GR","code"=>"300"},{"name"=>"Greenland","alpha"=>"GL","code"=>"304"},{"name"=>"Grenada","alpha"=>"GD","code"=>"308"},{"name"=>"Guadeloupe","alpha"=>"GP","code"=>"312"},{"name"=>"Guam","alpha"=>"GU","code"=>"316"},{"name"=>"Guatemala","alpha"=>"GT","code"=>"320"},{"name"=>"Guernsey","alpha"=>"GG","code"=>"831"},{"name"=>"Guinea","alpha"=>"GN","code"=>"324"},{"name"=>"Guinea-Bissau","alpha"=>"GW","code"=>"624"},{"name"=>"Guyana","alpha"=>"GY","code"=>"328"}])
Country.create([{"name"=>"Haiti","alpha"=>"HT","code"=>"332"},{"name"=>"Heard Island and McDonald Islands","alpha"=>"HM","code"=>"334"},{"name"=>"Holy See (Vatican City State)","alpha"=>"VA","code"=>"336"},{"name"=>"Honduras","alpha"=>"HN","code"=>"340"},{"name"=>"Hong Kong","alpha"=>"HK","code"=>"344"},{"name"=>"Hungary","alpha"=>"HU","code"=>"348"}])
Country.create([{"name"=>"Iceland","alpha"=>"IS","code"=>"352"},{"name"=>"India","alpha"=>"IN","code"=>"356"},{"name"=>"Indonesia","alpha"=>"ID","code"=>"360"},{"name"=>"Iran, Islamic Republic of","alpha"=>"IR","code"=>"364"},{"name"=>"Iraq","alpha"=>"IQ","code"=>"368"},{"name"=>"Ireland","alpha"=>"IE","code"=>"372"},{"name"=>"Isle of Man","alpha"=>"IM","code"=>"833"},{"name"=>"Israel","alpha"=>"IL","code"=>"376"},{"name"=>"Italy","alpha"=>"IT","code"=>"380"}])
Country.create([{"name"=>"Jamaica","alpha"=>"JM","code"=>"388"},{"name"=>"Japan","alpha"=>"JP","code"=>"392"},{"name"=>"Jersey","alpha"=>"JE","code"=>"832"},{"name"=>"Jordan","alpha"=>"JO","code"=>"400"},{"name"=>"Kazakhstan","alpha"=>"KZ","code"=>"398"},{"name"=>"Kenya","alpha"=>"KE","code"=>"404"},{"name"=>"Kiribati","alpha"=>"KI","code"=>"296"},{"name"=>"Korea, Democratic People's Republic of","alpha"=>"KP","code"=>"408"},{"name"=>"Korea, Republic of","alpha"=>"KR","code"=>"410"},{"name"=>"Kuwait","alpha"=>"KW","code"=>"414"},{"name"=>"Kyrgyzstan","alpha"=>"KG","code"=>"417"}])
Country.create([{"name"=>"Lao People's Democratic Republic","alpha"=>"LA","code"=>"418"},{"name"=>"Latvia","alpha"=>"LV","code"=>"428"},{"name"=>"Lebanon","alpha"=>"LB","code"=>"422"},{"name"=>"Lesotho","alpha"=>"LS","code"=>"426"},{"name"=>"Liberia","alpha"=>"LR","code"=>"430"},{"name"=>"Libya","alpha"=>"LY","code"=>"434"},{"name"=>"Liechtenstein","alpha"=>"LI","code"=>"438"},{"name"=>"Lithuania","alpha"=>"LT","code"=>"440"},{"name"=>"Luxembourg","alpha"=>"LU","code"=>"442"}])
Country.create([{"name"=>"Macao","alpha"=>"MO","code"=>"446"},{"name"=>"Macedonia, the former Yugoslav Republic of","alpha"=>"MK","code"=>"807"},{"name"=>"Madagascar","alpha"=>"MG","code"=>"450"},{"name"=>"Malawi","alpha"=>"MW","code"=>"454"},{"name"=>"Malaysia","alpha"=>"MY","code"=>"458"},{"name"=>"Maldives","alpha"=>"MV","code"=>"462"},{"name"=>"Mali","alpha"=>"ML","code"=>"466"},{"name"=>"Malta","alpha"=>"MT","code"=>"470"},{"name"=>"Marshall Islands","alpha"=>"MH","code"=>"584"},{"name"=>"Martinique","alpha"=>"MQ","code"=>"474"},{"name"=>"Mauritania","alpha"=>"MR","code"=>"478"},{"name"=>"Mauritius","alpha"=>"MU","code"=>"480"},{"name"=>"Mayotte","alpha"=>"YT","code"=>"175"},{"name"=>"Mexico","alpha"=>"MX","code"=>"484"},{"name"=>"Micronesia, Federated States of","alpha"=>"FM","code"=>"583"},{"name"=>"Moldova, Republic of","alpha"=>"MD","code"=>"498"},{"name"=>"Monaco","alpha"=>"MC","code"=>"492"},{"name"=>"Mongolia","alpha"=>"MN","code"=>"496"},{"name"=>"Montenegro","alpha"=>"ME","code"=>"499"},{"name"=>"Montserrat","alpha"=>"MS","code"=>"500"},{"name"=>"Morocco","alpha"=>"MA","code"=>"504"},{"name"=>"Mozambique","alpha"=>"MZ","code"=>"508"},{"name"=>"Myanmar","alpha"=>"MM","code"=>"104"}])
Country.create([{"name"=>"Namibia","alpha"=>"NA","code"=>"516"},{"name"=>"Nauru","alpha"=>"NR","code"=>"520"},{"name"=>"Nepal","alpha"=>"NP","code"=>"524"},{"name"=>"Netherlands","alpha"=>"NL","code"=>"528"},{"name"=>"New Caledonia","alpha"=>"NC","code"=>"540"},{"name"=>"New Zealand","alpha"=>"NZ","code"=>"554"},{"name"=>"Nicaragua","alpha"=>"NI","code"=>"558"},{"name"=>"Niger","alpha"=>"NE","code"=>"562"},{"name"=>"Nigeria","alpha"=>"NG","code"=>"566"},{"name"=>"Niue","alpha"=>"NU","code"=>"570"},{"name"=>"Norfolk Island","alpha"=>"NF","code"=>"574"},{"name"=>"Northern Mariana Islands","alpha"=>"MP","code"=>"580"},{"name"=>"Norway","alpha"=>"NO","code"=>"578"}])
Country.create([{"name"=>"Oman","alpha"=>"OM","code"=>"512"}])
Country.create([{"name"=>"Pakistan","alpha"=>"PK","code"=>"586"},{"name"=>"Palau","alpha"=>"PW","code"=>"585"},{"name"=>"Palestinian Territory, Occupied","alpha"=>"PS","code"=>"275"},{"name"=>"Panama","alpha"=>"PA","code"=>"591"},{"name"=>"Papua New Guinea","alpha"=>"PG","code"=>"598"},{"name"=>"Paraguay","alpha"=>"PY","code"=>"600"},{"name"=>"Peru","alpha"=>"PE","code"=>"604"},{"name"=>"Philippines","alpha"=>"PH","code"=>"608"},{"name"=>"Pitcairn","alpha"=>"PN","code"=>"612"},{"name"=>"Poland","alpha"=>"PL","code"=>"616"},{"name"=>"Portugal","alpha"=>"PT","code"=>"620"},{"name"=>"Puerto Rico","alpha"=>"PR","code"=>"630"}])
Country.create([{"name"=>"Qatar","alpha"=>"QA","code"=>"634"}])
Country.create([{"name"=>"Réunion","alpha"=>"RE","code"=>"638"},{"name"=>"Romania","alpha"=>"RO","code"=>"642"},{"name"=>"Russian Federation","alpha"=>"RU","code"=>"643"},{"name"=>"Rwanda","alpha"=>"RW","code"=>"646"}])
Country.create([{"name"=>"Saint Barthélemy","alpha"=>"BL","code"=>"652"},{"name"=>"Saint Helena, Ascension and Tristan da Cunha","alpha"=>"SH","code"=>"654"},{"name"=>"Saint Kitts and Nevis","alpha"=>"KN","code"=>"659"},{"name"=>"Saint Lucia","alpha"=>"LC","code"=>"662"},{"name"=>"Saint Martin (French part)","alpha"=>"MF","code"=>"663"},{"name"=>"Saint Pierre and Miquelon","alpha"=>"PM","code"=>"666"},{"name"=>"Saint Vincent and the Grenadines","alpha"=>"VC","code"=>"670"},{"name"=>"Samoa","alpha"=>"WS","code"=>"882"},{"name"=>"San Marino","alpha"=>"SM","code"=>"674"},{"name"=>"Sao Tome and Principe","alpha"=>"ST","code"=>"678"},{"name"=>"Saudi Arabia","alpha"=>"SA","code"=>"682"},{"name"=>"Senegal","alpha"=>"SN","code"=>"686"},{"name"=>"Serbia","alpha"=>"RS","code"=>"688"},{"name"=>"Seychelles","alpha"=>"SC","code"=>"690"},{"name"=>"Sierra Leone","alpha"=>"SL","code"=>"694"},{"name"=>"Singapore","alpha"=>"SG","code"=>"702"},{"name"=>"Sint Maarten (Dutch part)","alpha"=>"SX","code"=>"534"},{"name"=>"Slovakia","alpha"=>"SK","code"=>"703"},{"name"=>"Slovenia","alpha"=>"SI","code"=>"705"},{"name"=>"Solomon Islands","alpha"=>"SB","code"=>"090"},{"name"=>"Somalia","alpha"=>"SO","code"=>"706"},{"name"=>"South Africa","alpha"=>"ZA","code"=>"710"},{"name"=>"South Georgia and the South Sandwich Islands","alpha"=>"GS","code"=>"239"},{"name"=>"South Sudan","alpha"=>"SS","code"=>"728"},{"name"=>"Spain","alpha"=>"ES","code"=>"724"},{"name"=>"Sri Lanka","alpha"=>"LK","code"=>"144"},{"name"=>"Sudan","alpha"=>"SD","code"=>"729"},{"name"=>"Suriname","alpha"=>"SR","code"=>"740"},{"name"=>"Svalbard and Jan Mayen","alpha"=>"SJ","code"=>"744"},{"name"=>"Swaziland","alpha"=>"SZ","code"=>"748"},{"name"=>"Sweden","alpha"=>"SE","code"=>"752"},{"name"=>"Switzerland","alpha"=>"CH","code"=>"756"},{"name"=>"Syrian Arab Republic","alpha"=>"SY","code"=>"760"}])
Country.create([{"name"=>"Taiwan, Province of China","alpha"=>"TW","code"=>"158"},{"name"=>"Tajikistan","alpha"=>"TJ","code"=>"762"},{"name"=>"Tanzania, United Republic of","alpha"=>"TZ","code"=>"834"},{"name"=>"Thailand","alpha"=>"TH","code"=>"764"},{"name"=>"Timor-Leste","alpha"=>"TL","code"=>"626"},{"name"=>"Togo","alpha"=>"TG","code"=>"768"},{"name"=>"Tokelau","alpha"=>"TK","code"=>"772"},{"name"=>"Tonga","alpha"=>"TO","code"=>"776"},{"name"=>"Trinidad and Tobago","alpha"=>"TT","code"=>"780"},{"name"=>"Tunisia","alpha"=>"TN","code"=>"788"},{"name"=>"Turkey","alpha"=>"TR","code"=>"792"},{"name"=>"Turkmenistan","alpha"=>"TM","code"=>"795"},{"name"=>"Turks and Caicos Islands","alpha"=>"TC","code"=>"796"},{"name"=>"Tuvalu","alpha"=>"TV","code"=>"798"}])
Country.create([{"name"=>"Uganda","alpha"=>"UG","code"=>"800"},{"name"=>"Ukraine","alpha"=>"UA","code"=>"804"},{"name"=>"United Arab Emirates","alpha"=>"AE","code"=>"784"},{"name"=>"United Kingdom","alpha"=>"GB","code"=>"826"},{"name"=>"United States","alpha"=>"US","code"=>"840"},{"name"=>"United States Minor Outlying Islands","alpha"=>"UM","code"=>"581"},{"name"=>"Uruguay","alpha"=>"UY","code"=>"858"},{"name"=>"Uzbekistan","alpha"=>"UZ","code"=>"860"}])
Country.create([{"name"=>"Vanuatu","alpha"=>"VU","code"=>"548"},{"name"=>"Venezuela, Bolivarian Republic of","alpha"=>"VE","code"=>"862"},{"name"=>"Viet Nam","alpha"=>"VN","code"=>"704"},{"name"=>"Virgin Islands, British","alpha"=>"VG","code"=>"092"},{"name"=>"Virgin Islands, U.S.","alpha"=>"VI","code"=>"850"}])
Country.create([{"name"=>"Wallis and Futuna","alpha"=>"WF","code"=>"876"},{"name"=>"Western Sahara","alpha"=>"EH","code"=>"732"}])
Country.create([{"name"=>"Yemen","alpha"=>"YE","code"=>"887"}])
Country.create([{"name"=>"Zambia","alpha"=>"ZM","code"=>"894"},{"name"=>"Zimbabwe","alpha"=>"ZW","code"=>"716"}])